// GENERATED by `just api` from dsj/ui/schemas.py. DO NOT EDIT: change the Python models, then run `just api`.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recordings
         * @description Every recording dsj knows: none, until the store (#105) and the page (#156).
         */
        get: operations["list_recordings_api_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Recording
         * @description One recording, wherever it was last seen, with every transcript of it.
         */
        Recording: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes: number | null;
            /** Duration S */
            duration_s: number | null;
            /** Content Id */
            content_id: string | null;
            /** Audio Codec */
            audio_codec: string | null;
            /** Video Codec */
            video_codec: string | null;
            /** First Seen */
            first_seen: string;
            /** Missing */
            missing: boolean;
            /** Transcripts */
            transcripts: components["schemas"]["Transcript"][];
        };
        /**
         * Transcript
         * @description One transcript of a recording, as the library page lists it.
         */
        Transcript: {
            /** Id */
            id: number;
            /** Finished At */
            finished_at: string;
            /** Engine */
            engine: string | null;
            /** Model */
            model: string;
            /** Diarized */
            diarized: boolean | null;
            /** Speaker Count */
            speaker_count: number | null;
            /** Mark Count */
            mark_count: number | null;
            /** Language */
            language: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_recordings_api_recordings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"][];
                };
            };
        };
    };
}
