// GENERATED by `just api` from dsj/ui/schemas.py. DO NOT EDIT: change the Python models, then run `just api`.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recordings
         * @description Every recording, the one with the newest transcript first, each with its transcripts.
         */
        get: operations["recordings_api_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Recording
         * @description Ask for a recording in the Mac's file dialog and add it to the library, copying nothing.
         *
         *     The library keeps where the file is and reads it there (#110). The same
         *     contents picked again, from anywhere, are the row the library already
         *     has. A file ffprobe cannot read is added all the same, with what ffprobe
         *     said, so the page can show it. None when the dialog was cancelled.
         */
        post: operations["import_recording_api_recordings_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/relink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Relink
         * @description Ask where a moved recording is now, and point its row there if the contents match.
         *
         *     Every transcript stays on the row, so it opens and plays again (#105's
         *     relink). A file with other contents is refused and nothing changes. None
         *     when the dialog was cancelled.
         */
        post: operations["relink_api_recordings__recording_id__relink_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transcripts/{transcript_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transcript
         * @description One transcript's JSON, byte for byte as the file holds it.
         *
         *     The id is taken as text and checked here rather than typed `int`, so that
         *     anything but a plain number (`..`, `-1`, `1.0`) is the same 404 as an id the
         *     library has never had, and never a 422 that echoes the input back.
         */
        get: operations["transcript_api_transcripts__transcript_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recording/{recording_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Media
         * @description The recording's file, whole or by the byte range the request asks for.
         *
         *     With `sound=true`, a copy of its sound in a form every browser plays, for
         *     a file the browser refused (#110): AV1 video in WebKit, or a container no
         *     browser opens. Made once, on the first such request, and kept beside the
         *     library; the recording itself is never changed.
         */
        get: operations["media_api_recording__recording_id__media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recording/{recording_id}/waveform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Waveform
         * @description The shape of the recording's sound, for the page to draw without decoding it (#61).
         *
         *     Pairs of signed bytes, min then max, ENVELOPE_RATE buckets a second
         *     (dsj.media.envelope). Computed once per recording and kept on disk; every
         *     later request reads the file.
         */
        get: operations["waveform_api_recording__recording_id__waveform_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Engines
         * @description Every engine, each with the reason it cannot run here, or none.
         *
         *     Asked again on every call rather than once at startup: installing an extra
         *     and reopening the picker should show it, with no restart.
         */
        get: operations["engines_api_engines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jobs
         * @description Every transcription this server has started, the first first.
         */
        get: operations["jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe
         * @description Start transcribing one recording of the library; answered once the run is queued.
         *
         *     The id is checked as text, as the transcript route checks it, so anything
         *     but a plain number is the same 404 as an id the library never had.
         */
        post: operations["transcribe_api_recordings__recording_id__transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Heartbeat
         * @description The page is still open. The guard has already counted the request.
         */
        post: operations["heartbeat_api_heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Engine
         * @description One engine the picker offers, and whether it can run on this machine.
         */
        Engine: {
            name: components["schemas"]["EngineName"];
            /** Reason */
            reason: string | null;
            /** Default Model */
            default_model: string;
        };
        /** @enum {string} */
        EngineName: "parakeet" | "whisper" | "sherpa";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Job
         * @description A transcription started from the page, as its last status frame and its outcome say.
         */
        Job: {
            /** Id */
            id: number;
            /** Recording Id */
            recording_id: number;
            engine: components["schemas"]["EngineName"];
            /** Model */
            model: string;
            /** Language */
            language: string | null;
            /** Reports Progress */
            reports_progress: boolean;
            /** Started At */
            started_at: string;
            state: components["schemas"]["JobState"];
            /** Fraction */
            fraction: number;
            /** Audio Done S */
            audio_done_s: number;
            /** Audio Total S */
            audio_total_s: number;
            /** Elapsed S */
            elapsed_s: number;
            /** Speed */
            speed: number;
            /** Eta S */
            eta_s: number | null;
            /** Stalled S */
            stalled_s: number | null;
            /** Error */
            error: string | null;
            /** Transcript Id */
            transcript_id: number | null;
            /** Notes */
            notes: string[];
        };
        /** @enum {string} */
        JobState: "starting" | "extracting" | "running" | "retrying" | "diarizing" | "saving" | "done" | "failed";
        /**
         * Recording
         * @description One recording, wherever it was last seen, with every transcript of it.
         */
        Recording: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes: number | null;
            /** Duration S */
            duration_s: number | null;
            /** Content Id */
            content_id: string | null;
            /** Audio Codec */
            audio_codec: string | null;
            /** Video Codec */
            video_codec: string | null;
            /** First Seen */
            first_seen: string;
            /** Missing */
            missing: boolean;
            /** Unreadable */
            unreadable: string | null;
            /** Transcripts */
            transcripts: components["schemas"]["Transcript"][];
        };
        /**
         * TranscribeRequest
         * @description What the page sends to start a transcription: the flags of `dsj suno`, as values.
         */
        TranscribeRequest: {
            /** @default parakeet */
            engine: components["schemas"]["EngineName"];
            /** Model */
            model?: string | null;
            /** Language */
            language?: string | null;
            /** Prompt */
            prompt?: string | null;
            /**
             * Roman Urdu
             * @default false
             */
            roman_urdu: boolean;
            /**
             * Diarize
             * @default true
             */
            diarize: boolean;
            /**
             * Require Diarize
             * @default false
             */
            require_diarize: boolean;
            /**
             * Start Over
             * @default false
             */
            start_over: boolean;
        };
        /**
         * Transcript
         * @description One transcript of a recording, as the library page lists it.
         */
        Transcript: {
            /** Id */
            id: number;
            /** Finished At */
            finished_at: string;
            /** Engine */
            engine: string | null;
            /** Model */
            model: string;
            /** Diarized */
            diarized: boolean | null;
            /** Speaker Count */
            speaker_count: number | null;
            /** Mark Count */
            mark_count: number | null;
            /** Language */
            language: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recordings_api_recordings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"][];
                };
            };
        };
    };
    import_recording_api_recordings_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"] | null;
                };
            };
        };
    };
    relink_api_recordings__recording_id__relink_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcript_api_transcripts__transcript_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    media_api_recording__recording_id__media_get: {
        parameters: {
            query?: {
                sound?: boolean;
            };
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/*": unknown;
                    "video/*": unknown;
                };
            };
            /** @description a range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    waveform_api_recording__recording_id__waveform_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    engines_api_engines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Engine"][];
                };
            };
        };
    };
    jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    transcribe_api_recordings__recording_id__transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heartbeat_api_heartbeat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
